Millie/Millie.Web/Controllers/BarCarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Millie.Web.Controllers
{
    public class BarCarController : Controller
    {
        // GET: BarCar
        public ActionResult Index()
        {
            // New up the game state and room
            Game.GameState gameState = Helpers.GameStateStorage.GetGameState();
            Game.BarCarRoom barCarRoom = new Game.BarCarRoom();

            // Build up a view model
            var viewModel = new Models.BarCarViewModel();
            viewModel.Description = barCarRoom.GetDescription(gameState);

            // Store the game state
            Helpers.GameStateStorage.StoreGameState(gameState);

            // Get the choices view model
            List<Game.PlayerChoice> choices = barCarRoom.GetChoices(gameState);
            foreach (Game.PlayerChoice choice in choices)
            {
                // Convert the choice into a choice view model
                var playerChoiceViewModel = new Models.PlayerChoiceViewModel(choice);
                viewModel.Choices.Add(playerChoiceViewModel);
            }

            // Return the view
            return View("Index", viewModel);
        }

        public ActionResult ProcessChoice(int choiceId)
        {
            // Get the game state and the room
            var barCarRoom = new Game.BarCarRoom();
            var gameState = Helpers.GameStateStorage.GetGameState();

            // Process the choice
            var result = barCarRoom.ProcessChoice(gameState, choiceId);

            // Store the game state back in cache
            Helpers.GameStateStorage.StoreGameState(gameState);

            // Store the result in the view bag
            ViewBag.ProcessChoiceResponse = result;

            // Return the view
            return Index();
        }
    }
}

Millie/Millie.Web/Controllers/BeardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Millie.Web.Controllers
{
    public class BeardController : Controller
    {
        // GET: Beard
        public ActionResult Status()
        {
            // Grab the game state
            var gameState = Helpers.GameStateStorage.GetGameState();

            // Build up the view model
            var viewModel = new Models.BeardStatusViewModel { BeardLength = gameState.BeardLength };

            return View(viewModel);
        }
    }
}

Millie/Millie.Web/Controllers/MainTentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Millie.Web.Controllers
{
    public class MainTentController : Controller
    {
        // GET: MainTent
        public ActionResult Index()
        {
            // New up the game state and room
            Game.GameState gameState = Helpers.GameStateStorage.GetGameState();
            Game.MainTentRoom mainTentRoom = new Game.MainTentRoom();

            // Build up a view model
            var viewModel = new Models.MainTentViewModel();
            viewModel.Description = mainTentRoom.GetDescription(gameState);

            // Store the game state
            Helpers.GameStateStorage.StoreGameState(gameState);

            // Get the choices view model
            List<Game.PlayerChoice> choices = mainTentRoom.GetChoices(gameState);
            foreach (Game.PlayerChoice choice in choices)
            {
                // Convert the choice into a choice view model
                var playerChoiceViewModel = new Models.PlayerChoiceViewModel(choice);
                viewModel.Choices.Add(playerChoiceViewModel);
            }

            // Return the view
            return View("Index", viewModel);
        }

        public ActionResult ProcessChoice(int choiceId)
        {
            // Get the game state and the room
            var mainTentRoom = new Game.MainTentRoom();
            var gameState = Helpers.GameStateStorage.GetGameState();

            // Process the choice
            var result = mainTentRoom.ProcessChoice(gameState, choiceId);

            // Store the game state back in cache
            Helpers.GameStateStorage.StoreGameState(gameState);

            // Store the result in the view bag
            ViewBag.ProcessChoiceResponse = result;

            // Return the view
            return Index();
        }
    }
}

Millie/Millie.Web/Controllers/TrapezeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Millie.Web.Controllers
{
    public class TrapezeController : Controller
    {
        // GET: Trapeze
        public ActionResult Index()
        {
            // New up the game state and room
            Game.GameState gameState = Helpers.GameStateStorage.GetGameState();
            Game.TrapezeRoom trapezeRoom = new Game.TrapezeRoom();

            // Build up a view model
            var viewModel = new Models.TrapezeViewModel();
            viewModel.Description = trapezeRoom.GetDescription(gameState);

            // Store the game state
            Helpers.GameStateStorage.StoreGameState(gameState);

            // Get the choices view model
            List<Game.PlayerChoice> choices = trapezeRoom.GetChoices(gameState);
            foreach (Game.PlayerChoice choice in choices)
            {
                // Convert the choice into a choice view model
                var playerChoiceViewModel = new Models.PlayerChoiceViewModel(choice);
                viewModel.Choices.Add(playerChoiceViewModel);
            }

            // Return the view
            return View("Index", viewModel);
        }

        public ActionResult ProcessChoice(int choiceId)
        {
            // Get the game state and the room
            var trapezeRoom = new Game.TrapezeRoom();
            var gameState = Helpers.GameStateStorage.GetGameState();

            // Process the choice
            var result = trapezeRoom.ProcessChoice(gameState, choiceId);

            // Store the game state back in cache
            Helpers.GameStateStorage.StoreGameState(gameState);

            // Store the result in the view bag
            ViewBag.ProcessChoiceResponse = result;

            // Return the view
            return Index();
        }
    }
}

Millie/Millie.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Millie the Bearded Lady</title>

    <link href='https://fonts.googleapis.com/css?family=Vast+Shadow|Oswald:400,300,700|Josefin+Slab:400,300,700' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>



    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-fixed-top millie-header">
        <div class="container-fluid">

            <div class="row">

                <div class="col-xs-2">

                    <a href="#menu-toggle" id="menu-toggle">Toggle Stats</a>
                </div>

                <div class="col-xs-8">
                    <h1 class="hidden-md hidden-sm hidden-xs">
                        Millie <span>the</span> Bearded Lady
                    </h1>
                    <h1 class="hidden-lg">
                        Millie
                    </h1>
                </div>

                <div class="col-xs-2">

                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                   
                        <div class="navbar-header page-scroll">

                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                    </button>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="hidden">
                                <a href="#page-top"></a>
                            </li>
                            <li class="page-scroll">
                                <div class="reset">
                                    
                                        @Html.ActionLink("Reset", "ResetGameState", "Home") 
                                    
                                </div>
                            </li>
                        </ul>
                    </div>
                    <!-- /.navbar-collapse -->

                </div>
            </div>



        </div>

        </div>
        <!-- /.container-fluid -->
    </nav>


    <div id="wrapper">


        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            @{ Html.RenderAction("Status", "Beard"); }
        </div>
        <!-- /#sidebar-wrapper -->
        <!-- Page Content -->
        <div id="page-content-wrapper">

            <!-- Start Room Navigation -->
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-3 col-md-6">
                        <div class="room-nav barcar">
                            @Html.ActionLink("Bar Car", "Index", "BarCar")
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <div class="room-nav tattooparlor">
                            @Html.ActionLink("Tattoo Room", "Index", "TattooRoom")
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <div class="room-nav maintent">
                            @Html.ActionLink("Main Tent", "Index", "MainTent")
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <div class="room-nav final">
                            @Html.ActionLink("The Trapeze", "Index", "Trapeze")
                        </div>
                    </div>
                </div>
            </div>
            <!-- End Room Navigation -->

            <div class="container-fluid">
                <div class="row">

                    <div class="col-lg-12">
                        <div class="story-content">
                                                      
                                @RenderBody()
                        
                        </div>
                    </div>

                </div>
            </div>
        </div>
        <!-- /#page-content-wrapper -->

    </div>
    <!-- /#wrapper -->
    <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    <!-- Menu Toggle Script -->
    <script>
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
    </script>



<!--   <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    
                </ul>
               
            </div>
        </div>
    </div>
    

   
    -->
</body>
</html>